# Generated by Django 5.2.11 on 2026-03-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_description_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('qop', 'Qop'), ('dona', 'Dona'), ('kg', 'KG'), ('m', 'Metr'), ('m2', 'Metr kvadrat')], max_length=10),
        ),
        migrations.CreateModel(
            name='StoreRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_ratings', to='core.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.store')),
            ],
            options={
                'db_table': 'store_ratings',
                'unique_together': {('store', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='StoreWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='core.store')),
            ],
            options={
                'db_table': 'store_working_hours',
                'ordering': ['day_of_week'],
                'unique_together': {('store', 'day_of_week')},
            },
        ),
    ]
