# Generated by Django 5.2.11 on 2026-03-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_store_description_store_phone_alter_product_unit_and_more'),
        ('core', '0004_storerating_storeworkinghours_product_search_vector_and_more'),
    ]

    operations = [
    ]
