# Generated by Django 5.2.11 on 2026-03-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260305_1527'),
        ('core', '0006_searchterm_product_installment_price_and_more'),
    ]

    operations = [
    ]
