# Generated by Django 5.2.10 on 2026-03-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_icon_alter_category_store'),
        ('core', '0007_merge_20260306_1100'),
    ]

    operations = [
    ]
