name: 🚀 Deploy BuildGo (Backend + Bot)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e

            echo "📂 Enter project"
            cd /var/www/builgo_backend

            echo "🔄 Git pull"
            git pull origin main

            echo "🐍 Activate venv"
            source venv/bin/activate

            echo "📦 Install deps"
            pip install -r requirements.txt

            echo "🧱 Django migrate"
            python manage.py migrate

            echo "🎨 Collect static"
            python manage.py collectstatic --noinput

            echo "🔁 Restart gunicorn"
            systemctl restart gunicorn

            echo "🤖 Restart telegram bot"
            systemctl restart buildgo-bot

            echo "✅ Deploy finished"
