name: Deploy BuildGo Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e

            echo "🔄 Going to project directory"
            cd /var/www/buildgo_backend

            echo "📥 Pull latest code"
            git pull origin main

            echo "🐍 Activate virtualenv"
            source venv/bin/activate

            echo "📦 Install dependencies"
            pip install -r requirements.txt

            echo "🗄️ Run migrations"
            python manage.py migrate

            echo "🎨 Collect static files"
            python manage.py collectstatic --noinput

            echo "♻️ Restart services"
            systemctl restart gunicorn
            systemctl restart buildgo-bot

            echo "✅ Deploy finished successfully"
